image:
  file: .gitpod.Dockerfile

tasks:
- before: |
    export PATH=$ANDROID_HOME/bin:$ANDROID_HOME/platform-tools:$PATH
  init: |
    echo "Init Flutter..."
    cd /workspace/chat-flutter-app
    flutter upgrade
    flutter doctor --android-licenses
    flutter pub get
  command: |
    flutter pub upgrade
    echo "Ready to go!"
    flutter doctor
vscode:
  extensions:
    - Dart-Code.dart-code@3.12.2:U4I/KVVS4Adq5Ain/7bqhg==
    - Dart-Code.flutter@3.12.2:8+9OCbCxNozE+NHjTY4Ubw==