image:
  file: .gitpod.Dockerfile

tasks:
  - init: flutter pub get
    command: flutter run -d web-server --web-port 8000 --debug

vscode:
  extensions:
    - Dart-Code.dart-code@3.12.2:U4I/KVVS4Adq5Ain/7bqhg==
    - Dart-Code.flutter@3.12.2:8+9OCbCxNozE+NHjTY4Ubw==